"""add flow_data to approval_flows

Revision ID: c5366b0f5a4b
Revises: 001
Create Date: 2026-02-11 21:54:00.438306

"""
from alembic import op
import sqlalchemy as sa


revision = 'c5366b0f5a4b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_flows', sa.Column('flow_data', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'user_approval_roles', 'approval_roles', ['approval_role_id'], ['id'])
    op.create_foreign_key(None, 'user_approval_roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_approval_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_approval_roles', type_='foreignkey')
    op.drop_column('approval_flows', 'flow_data')
    # ### end Alembic commands ###
